export const reels = [
  {src: 'videos/A12.webm', id: '27'},
  {src: 'videos/V1.webm', id: '26'},
  {src: 'videos/V3.webm', id: '25'},
  {src: 'videos/V4.webm', id: '24'},
  {src: 'videos/V5.webm', id: '23'},
  {src: 'videos/V6.webm', id: '22'},
  {src: 'videos/V7.webm', id: '21'},
  {src: 'videos/V8.webm', id: '20'},
  {src: 'videos/A4.webm', id: '19'},
  {src: 'videos/V3.webm', id: '18'},
  {src: 'videos/A8.webm', id: '17'},
  {src: 'videos/V4.webm', id: '16'},
  {src: 'videos/A5.webm', id: '15'},
  {src: 'videos/V6.webm', id: '14'},
  {src: 'videos/V7.webm', id: '13'},
  {src: 'videos/A13.webm', id: '12'},
  {src: 'videos/V8.webm', id: '10'},
  {src: 'videos/A1.webm', id: '9'},
  {src: 'videos/V2.webm', id: '8'},
  {src: 'videos/A3.webm', id: '7'},
  {src: 'videos/A5.webm', id: '6'},
  {src: 'videos/A6.webm', id: '5'},
  {src: 'videos/A7.webm', id: '4'},
  {src: 'videos/A8.webm', id: '3'},
  {src: 'videos/A9.webm', id: '2'},
  {src: 'videos/A11.webm', id: '1'},
]

export const reviews = [
  {id: '1', name: 'Somrat', company: 'Founder', content: 'Highly recommending, I have been working with this guy since 2020.'},
  {id: '2', name: 'Radhakrishnan', company: 'Doctor', content: 'Your edits are really good.'},
  {id: '3', name: 'Disha', company: 'Doctor', content: 'Your reel edits are awesome, thank you.'},
  {id: '4', name: 'Vishal', company: 'Real Estate', content: 'Amazing, your edits are so good..'},
  {id: '5', name: 'Shruti', company: 'Creator', content: 'Unique style!!'},
  {id: '6', name: 'Ali', company: 'Manager', content: 'We cracked a deal with your edits.'},
] 